name: raincat-test
version: 1.1.1.3
grade: stable
summary: A puzzle game with a cat in lead role.
description: "Raincat is a 2d puzzle game similar to the Incredible Machine and Lemmings series. Your goal is simple: guide the cat safe and dry to the end of each level. Just mind the rain, puddles, and loose fire hydrants in your path!"
icon: snap/gui/raincat-test.png
confinement: strict
base: core18

architectures:
- build-on: amd64
- build-on: arm64
- build-on: armhf
- build-on: ppc64el
- build-on: riscv64
- build-on: s390x

apps:
  raincat:
    extensions: [gnome-3-28]
    command: desktop-launch $SNAP/bin/raincat
    plugs:
      - alsa
      - audio-playback
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11

parts:
  raincat:
    plugin: dump
    source: https://github.com/styx/Raincat.git
    source-type: git
    source-commit: bfc94df91c604ea58b7cfac4a73373e9d010d04a
    override-build: |
      runhaskell Setup.lhs configure --prefix=/opt/raincat
      runhaskell Setup.lhs build
      runhaskell Setup.lhs install
    organize:
      /opt/raincat/bin/: bin/
      /opt/raincat/share/: share/
    build-packages:
      - ghc
      - libghc-extensible-exceptions-dev
      - libghc-glut-dev
      - libghc-mtl-dev
      - libghc-opengl-dev
      - libghc-random-dev
      - libghc-sdl-dev
      - libghc-sdl-image-dev
      - libghc-sdl-mixer-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libsdl-image1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl1.2-dev
    stage-packages:
      - freeglut3
      - libffi6
      - libgl1-mesa-glx
      - libglu1-mesa
      - libgmp10
      - libsdl-image1.2
      - libsdl-mixer1.2
      - libsdl1.2debian
      - libslang2

layout:
  /opt/raincat/share:
    symlink: $SNAP/share